### ISSUE TITLE
is there a working example?

### ISSUE THREAD

**Issue by apvlv** [copleykj/socialize-base-model#10]
Hello,

it would be very nice to have at least one complete working example of this..

Thank you!

**Comment by copleykj** [comment]
This is used extensively in all of the socialize packages.

**Comment by copleykj** [comment]
Is there something specific about this package that you would like to see demonstrated, or are you referring more generally to a working example that demonstrates the Socialize set of packages working together?

**Comment by apvlv** [comment]
I must admit that i'm not very familiar with meteor in general, although currently interested in meteor as a possible backend for my react-native app.  I'm interested to find best practices to design a backend for an app with social elements. Your packages seem very handy but i'm struggling to put it all together. So, yes, a complete working example with some of the Socialize packages that shows how you would structure your meteor app and  demonstrates them in action would be very very nice.   

Thank you for your response!

**Comment by copleykj** [comment]
I don't have any public repo that demonstrates these packages as of yet. I have every intention of having one, but each time I think I might have the time to put it together it just doesn't work out. For now I believe there are a couple projects by other users that use the packages and could be valuable resources.

https://github.com/ibrahimzahoor/meteor-messaging
https://github.com/StorytellerCZ/Socialize-starter
https://github.com/kaiyes/chatDemo

I'm in the process of some significant updates to the package set, as well at looking at potentially moving states at the moment.. If I can possibly squeeze in some work on a demo I will definitely do so. For now I hope these resources help.
