### ISSUE TITLE
[feature request] Add Astronomy support

### ISSUE THREAD

**Issue by StorytellerCZ** [copleykj/socialize-base-model#11]
When Base-model was created simple-schema was the only way to go with schemas. Now we also have Astronomy which has a growing support. 

It would be nice we simple-schema and Astronomy could be interchangeable.

**Comment by copleykj** [comment]
Doesn't astronomy kind of do what base-model does? Not sure there is any real way to do this without just moving everything to astronomy.

**Comment by StorytellerCZ** [comment]
Yes, there is overlap, but it would be good to be able to choose between Astronomy and Simple-schema. From the users point of view if they could choose either and then when defining schema passed in either of those formats that is all that is needed. That is, if it is feasible.

**Comment by copleykj** [comment]
I think this would be fine if astronomy was just the schema part, but it's the model part as well which is what base-model is.
