### ISSUE TITLE
Newest Version is incompatible with other packages

### ISSUE THREAD

**Issue by devlinpadayachee** [copleykj/socialize-base-model#12]
socialize:base-model*  downgraded from 1.0.0 to 0.4.0
socialize:user-model   added, version 0.1.7

**Comment by StorytellerCZ** [comment]
Yes. We should probably add some warning. @copleykj  How is the progress on getting the other packages up to date?

**Comment by copleykj** [comment]
Due to my unresolved housing issue necessitating higher income levels, I have focused solely on paid work lately and have not made any progress. Hopefully the situation will be resolved soon.

**Comment by anthonyboutinov** [comment]
Now ```readme.md``` code doesn't work, because projects like socialize:likeable use 0.4 version of the package. =(

I can't use code like
```
//Attach the collection to the model so we can save/update/delete
EventModel.attachCollection(Events);
```
It throws an exception.

**Comment by copleykj** [comment]
I'm working towards this now.. Hopefully thing progress along to the point of release before more work turns up :-P

**Comment by tjdfalcon** [comment]
One suggestion would be to migrate to the new collection2-core and node-simple-schema npm packages.  Thanks!

**Comment by StorytellerCZ** [comment]
Just got all the packages and will look into this.

**Comment by devlinpadayachee** [comment]
Hi Any chance you could update to the latest npm simpl-schema and collection-core modules

**Comment by copleykj** [comment]
Closing this as this should be moving towards resolution.
