### ISSUE TITLE
Cannot read property 'MeteorX' of undefined on *.meteor.com

### ISSUE THREAD

**Issue by awatson1978** [copleykj/socialize-base-model#4]
Hi!
Just a quick update.  I tried to deploy an app this morning to *.meteor.com using `socialize:base-model`, and got a broken site and the following errors in the client console (server console was fine).  

``` sh
Uncaught TypeError: Cannot read property 'MeteorX' of undefined(anonymous function)
Uncaught TypeError: Cannot read property 'ServiceConfiguration' of undefined(anonymous function) 
Uncaught ReferenceError: Spacebars is not defined
```

The `meteorhacks:unblock` and `meteorhacks:meteorx` dependencies seem to be causing a fuss. fyi.

-a

**Comment by lemonjp** [comment]
you can see this issue to find out your problem.
https://github.com/meteorhacks/meteorx/issues/5

**Comment by copleykj** [comment]
This should no longer be an issue as publications have been removed in favor of choice of join package and the unblock package has been removed from the deps
