### ISSUE TITLE
[feature request] Make .set() accept objects

### ISSUE THREAD

**Issue by StorytellerCZ** [copleykj/socialize-base-model#8]
`.set()` is great, but it only works for a single field. It would be great if it could also accept objects like so:

``` javascript
book.set({
  author: "authorId",
  title: "book title"
})
```

**Comment by copleykj** [comment]
I'm sure this is easily implemented, but honestly I'm going to have to dig into this code a bit and then slap the shit out of myself for not commenting this when I wrote it :-P
